### ISSUE TITLE
Feature request: preserve event_id if present

### ISSUE THREAD

**Issue by medlin01GA** [trichter/rf#10]
https://github.com/trichter/rf/blob/8fe5ac8458032850dc541501afbccc24b3e60a56/rf/rfstream.py#L55

I noticed the commented code here that preserves the event ID when iterating an event catalog. It would be helpful if this event ID was passed through from the original catalog data, if available.

**Comment by trichter** [comment]
Good idea, I do not know anymore why I changed this. I added some code to pass through the event ids, but those will only be written to H5 format at the moment. Please let me know if the changes work for you..

**Comment by medlin01GA** [comment]
Looks good to me.
