### ISSUE TITLE
Update plot_rf signature to allow passing kwargs on to savefig

### ISSUE THREAD

**Issue by medlin01GA** [trichter/rf#13]
Function signature of function `rf.imaging.plot_rf()` will be updated to pass kwargs on to `fig.savefig()`. This will allow more control over the image file parameters such as dpi resolution.

**Comment by medlin01GA** [comment]
Implemented in https://github.com/trichter/rf/pull/14.  (Sorry, I'm used to creating Issues first and then branching. Pity github can't create a branch directly from a ticket.)

**Comment by trichter** [comment]
> Implemented in #14. (Sorry, I'm used to creating Issues first and then branching. Pity github can't create a branch directly from a ticket.)

No problem. Not too much issues in this project ;). If you feel like you can convert an issue into a pull request with a POST command:
https://github.com/obspy/obspy/wiki/Interesting-Reading-on-Git%2C-GitHub

I close this issue. Let's discuss in the PR.
