### ISSUE TITLE
Gaussian filter issues

### ISSUE THREAD

**Issue by shearwavesplitter** [trichter/rf#15]
Hi there,

In the equation for the Gaussian low pass filter 
gauss = np.exp(np.maximum(-(0.5 * 2 * pi * freq / gauss) ** 2, -700.) -
                   1j * tshift * 2 * pi * freq)

I believe the 0.5 should be outside of the brackets: -0.5*( 2 * pi * freq / gauss) ** 2
per https://en.wikipedia.org/wiki/Gaussian_filter#Definition equation 4.

Also a related question, what's behind the choice of the Gauss parameter being 2pi times the standard deviation of the resulting Gaussian?

Cheers

**Comment by trichter** [comment]
Thanks a lot for these comments. I think you are right. I do not know anymore why I chose to write the 2pi in there. At least the frequency is correctly multiplied by 2pi for the shift. 

In the end its just a question how the gauss parameter is defined.
Probably it would best if the gauss parameter is somehow related to the cut-off frequency. I checked the behaviour with this code:
```py
import matplotlib.pyplot as plt
import numpy as np
from rf import read_rf
from rf.deconvolve import deconvf

stream = read_rf()[:3]
rsp = [tr.data for tr in stream]
src = stream.select(component='Z')[0].data
sr = stream[0].stats.sampling_rate  # 5 Hz
for gauss in (0.5, 1, 2):
    rf_data, info = deconvf(rsp, src, sr, gauss=gauss, return_info=True)
    freq = info['freq']
    g = np.abs(info['gauss'])
    indc = np.nonzero(g < 0.607)[0][0]  # 0.607 = exp(0.5)
    plt.plot(freq, g, label=f'gauss={gauss:.1f}  fc={freq[indc]:.2f}Hz')
plt.xlabel('frequency (Hz)')
plt.legend()
plt.savefig('gauss.png')
plt.show()
```

The result looks like this at the moment:
![gauss_old](https://user-images.githubusercontent.com/2046150/65515865-413bf600-dee0-11e9-9009-1658d8ed9ff4.png)

When I change the equation for the Gaussian low pass to `-0.5 * (freq / gauss) ** 2` as you suggested I get this image:
![gauss_new](https://user-images.githubusercontent.com/2046150/65516021-8829eb80-dee0-11e9-8004-3c32174cd810.png)

Here, the gauss parameter is clearly related to the cut-off frequency which I find intuitive. At the same time I will change the default from `gauss=2` to `gauss=0.5` to get similar default behavior as before.

Do you agree?

**Comment by shearwavesplitter** [comment]
Thank you for your detailed response! Your changes look good to me. 

Rather than referring to a cut-off frequency (`f_c`) I would refer to it as the standard deviation of the Gaussian (`σ_f`) to avoid confusion (as the two aren't necessarily equal). You could calculate `f_c` (e.g.  `f_c=0.8326*σ_f` from the same article), however the old Gauss parameter is just the standard deviation multiplied by some number so it makes sense to stick with using standard deviation. For the old `gauss=2`, the equivalent `σ_f=0.45`.

The old code is similar to equation two except `a` is not squared which probably makes it look quite different.

**Comment by trichter** [comment]
Thanks and closing.

**Comment by medlin01GA** [comment]
The cutoff freq is more intuitive after this change, thanks for the heads-up on this.
