### ISSUE TITLE
Consider passing RFTrace to deconv* function rather than raw numpy array

### ISSUE THREAD

**Issue by medlin01GA** [trichter/rf#17]
In function `rf.deconvolve.deconvolve()`, when the response data is gathered for passing on to the underlying deconvolution function (e.g. `deconvt` or `deconvf`), it is put into a list of numpy.array, as at line 113:
`rsp_data = [tr.data for tr in rsp]`

In my use case of a custom deconvolution function this works fine, however there are output metadata of the deconvolution process that ideally I would like to store with the traces. If the deconvolution function were passed `RFTrace` objects rather than `numpy.array`s then I could add the metadata to the `RFTrace.stats` container.

**Comment by trichter** [comment]
I see, it is not possible to return anything other than the deconvolved data, at the moment. I thought about other possibilities, e.g. appending other returned values of the deconv* functions to the Stream object, but that would be rather unusual and also would not help, if you have metadata to store with the traces. Since the possibility of using a custom deconv function was only recently added upon your request, I think it is no problem to change how the deconv* functions are called now. I'll have a look.

**Comment by trichter** [comment]
Hmm, well OK, custom deconvolution functions were introduced in version 0.5.0, which was published 2 years ago.

**Comment by medlin01GA** [comment]
Maybe I could achieve what I want by adding extra arguments that get collected in kwargs when I call rf(). Then in my custom deconv function I can extract those from kwargs and add my custom metadata into there.


________________________________

**Comment by trichter** [comment]
I changed the behaviour in deconvolve for the dev version. A RFStream is now passed to the custom deconv function and it assumes a Stream is returned. Thus, you now can use the RFTrace.stats object to store metadata.

> Maybe I could achieve what I want by adding extra arguments that get collected in kwargs when I call rf(). Then in my custom deconv function I can extract those from kwargs and add my custom metadata into there.

This is also a good idea. Just make sure that you use a mutable object, like dict or list. You don't need to extract from kwargs, just specify it directly.

```py
def custom_deconv(..., info={}):
    ...
    info['key'] = value
    ...

info = {}
stream.rf(..., deconvolve='func', func=custom_deconv, info=info)
print(info)
```

**Comment by trichter** [comment]
@medlin01GA 
Are these latest commits working for you?

**Comment by medlin01GA** [comment]
I have reviewed the code changes and added one comment. I haven't used the changes myself yet as I'm using release 0.8.0 and have not updated to dev, however they look like just what I was looking for in my custom deconvolution function.

**Comment by trichter** [comment]
Thanks for the feedback.
