### ISSUE TITLE
[JOSS review] Errors when install toeplitz

### ISSUE THREAD

**Issue by seisman** [trichter/rf#18]
I'm using macOS. I followed the install instructions (create an environment, and replace `gfortran_linux-64` with `gfortran_osx-64`), and had trouble installing the toeplitz package.

Please see the attached logfile [errors.log](https://github.com/trichter/rf/files/3785345/errors.log).

https://github.com/openjournals/joss-reviews/issues/1808

**Comment by trichter** [comment]
Does it help if you set  `NPY_DISTUTILS_APPEND_FLAGS` to 1?

```
export NPY_DISTUTILS_APPEND_FLAGS=1
```

**Comment by seisman** [comment]
Yes, it works!

**Comment by trichter** [comment]
Probably, this should be mentioned in the docs. I already set it in my .bashrc.
