### ISSUE TITLE
moveout for Sp

### ISSUE THREAD

**Issue by qwertz07** [trichter/rf#2]
Great job, but moveout for Sp doesn't work properly: 

In [177]: new_t = np.interp(t, t0, t1, left=0, right=0)
In [178]: new_t
Out[178]: array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

For Sp you have to change right to None:
           new_t = np.interp(t, t0, t1, left=0, right=None)

**Comment by trichter** [comment]
Thanks for the bug report and the suggested solution. I'll have a look into it.
