### ISSUE TITLE
rf.imaging.plot_rf() assumes all traces have same time points

### ISSUE THREAD

**Issue by medlin01GA** [trichter/rf#23]
When a stream is passed to `rf.imaging.plot_rf()`, the code assumes that all traces in the stream have the same time points, and the `times` array is generated from the first trace and assumed to be valid for all traces.

However it is possible occasionally for a trace to have different times if it has truncated data that makes the data array smaller than the time window of the other streams. If you try to plot such data, which should in principle be plottable, the function throws an error plotting the truncated trace, because the `times` points array is longer than the data array for that trace.

It would be better if the times array were computed per trace when plotting individual traces.

I'm not sure how the computing and plotting of the stacked trace should be handled in this situation. Possibly exclude the truncated trace from the stack, or else skip the stack plotting altogether.

**Comment by trichter** [comment]
Thank you for raising this issue. I pushed a fix to master. For now, I skipped plotting the stack in this case. If only some samples are missing another possibility is to use the trim option in plot_rf. The upcoming new obspy release also includes a stack method for stream. I will switch to the obspy version once it is released.

**Comment by trichter** [comment]
@medlin01GA feel free to reopen this issue if you are not completely satisfied with the solution.
