### ISSUE TITLE
How to use ppoints

### ISSUE THREAD

**Issue by Sarenrenegade** [trichter/rf#28]
Hi! I quite new to python and I'm having a hard time understanding how to use ppoint to find piercing points for SAC file with stream because I get an error "key error slowness"...
![error slowness](https://user-images.githubusercontent.com/68898650/88653608-98948f00-d0cc-11ea-829e-5f278cc824b5.PNG)
Can you help me out ? thanks

**Comment by trichter** [comment]
Hi, usage questions as these are more suited for the discourse forum [here](https://discourse.obspy.org/c/obspy-related-projects). Please open a new topic there with your question. Please also post the contents of `stream[0].stats` there.

The issue tracker is more for bug reports, feature requests, etc. Thanks.
