### ISSUE TITLE
Run test error

### ISSUE THREAD

**Issue by mohanpant44** [trichter/rf#36]
Hello, 
I installed rf as it is given in the documentation.  Any help will be of great help. 
<img width="808" alt="Screen Shot 2021-04-29 at 10 44 40 PM" src="https://user-images.githubusercontent.com/45698485/116649460-8639d100-a93c-11eb-8718-0adee672336b.png">

**Comment by trichter** [comment]
You have a problem with your numpy installation not related to rf. You could try the trouble shooting guide behind the link given in the error description. Or you try googling the error.
