### ISSUE TITLE
Compatibility of RFStream with seismic handler

### ISSUE THREAD

**Issue by FelixMSchneider** [trichter/rf#37]
Hi Tom!

I had some trouble to convert an obspy stream to rfstream. The "Q" file written from RFStream cannot be read by seismic handler, when the COMMENT is filled with a json dictionary.

Thus, as workaround I converted all Q-Files written from RFStream to be readable with seismic handler by replacing sh.COMMENT with "" (empty string) and writing station_lat, station_lon into DCVREG,DCVINCI header variables:
 
    for tr in st:
        tr.stats.sh.DCVREG   = tr.stats.station_latitude
        tr.stats.sh.DCVINCI  = tr.stats.station_longitude
        tr.stats.sh.COMMENT  = ""
    st.write(SH_RFFILE, format="Q")

Those Q-FIles can be read by seismic handler.
However reading those Q-Files again with obspy and trying to convert them back to RFStream-objects fails, since the COMMENT is empty. 

Error message:

    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I could fix this by replacing

                elif format == 'sh' and head_format == 'COMMENT':
                    st.update(json.loads(value))
                    continue

with

                elif format == 'sh' and head_format == 'COMMENT':
                    if len(value)>0:
                        st.update(json.loads(value))
                    continue

in _read_format_specific_header   in rfstream.py

**Comment by FelixMSchneider** [comment]
Actually for seismic handler the problem appears when quote signs (") are included in the COMMENT variable.

Thus, when writing an entry in the QHD File

    S000:{"station_latitude":33.3735287,"station_longitude":88.4932798,"phase":"P"}~

had to be replaced with

    S000:{station_latitude:33.3735287, station_longitude:88.4932798, phase:P}~

to be readable with seismic handler. However, this would not be suitable for json, I guess?

I already tested single quotes, but seismic handler cannot handle them too :(

**Comment by trichter** [comment]
Hi Felix!

I did not have this valid use case in mind.

For `rf->SeismicHandler`, I think simply not adding the `COMMENT` field or deleting it with `del tr.stats.sh.COMMENT` should work.


> which fails. I had to remove the quote signs inside the .QHD File. With this modified entry
> 
> ```
> S000:{station_latitude:33.3735287, station_longitude:88.4932798, phase:P}~
> ```

Since not many people are using Q files, I think we could simply leave the quote signs away. But on the other hand this is not valid JSON anymore and adds more complication when reading the file in with `rf`.

**Comment by trichter** [comment]
In the referenced PR, I added a `use_comment` flag for writing to turn of writing metadata to the COMMENT field.
Additionally, reading Q files is more robust by ignoring COMMENT fields without valid JSON.

Felix, maybe you could test these changes with your code.

**Comment by FelixMSchneider** [comment]
> 
> For `rf->SeismicHandler`, I think simply not adding the `COMMENT` field or deleting it with `del tr.stats.sh.COMMENT` should work.

Yes, when I delete the COMMENT with 

    del tr.stats.sh.COMMENT

instead of setting it to empty string, the obspy stream can be converted to rfstream. Thus, this workaround works without any changes...

**Comment by FelixMSchneider** [comment]
With this PR both directions are working, when I read/write new files.

However, if I want to convert an existing RFstream (where COMMENT is already filled with a json dict) I still have to manually delete the COMMENT value. 

I tried to do this with 

    import rf
    st=rf.read_rf("EVENTS_STATS.QHD")   
    st.write("EVENTS_STATS_SHC.QHD", use_comment=False, format="Q")  

    for tr in st:
         tr.stats.sh.DCVREG   = tr.stats.station_latitude
         tr.stats.sh.DCVINCI  = tr.stats.station_longitude
         del tr.stats.sh.COMMENT

     st.write("EVENTS_STATS_SHC2.QHD", use_comment=False, format="Q" )

EVENTS_STATS is not readable with seismic handler, since it was written using comment.
EVENTS_STATS_SHC is also not readable with seismic handler, since the comment is still filled
EVENTS_STATS_SHC2 is readable with seismic handler

**Comment by trichter** [comment]
I changed the flag name to `sh_compat` and it now simply deletes the COMMENT field and should result in a EVENTS_STATS_SHC file which is readable by SeismicHandler.

**Comment by FelixMSchneider** [comment]
I just tested this new version. It works nicely. Thank you!

**Comment by trichter** [comment]
Thanks for the suggestions, PR is merged.
