### ISSUE TITLE
It's important. Please fix this issue.

### ISSUE THREAD

**Issue by PawanGeo18** [trichter/rf#40]
I am running this code on python notebook 3.10.
I am getting following two errors,

AttributeError: can't set attribute 'collections'.

ImportError: cannot import name 'Iterable' from 'collections' (/home/seismology11/anaconda3/envs/myenv/lib/python3.10/collections/__init__.py)

Please tell me, how can i resolve this issue.

**Comment by PawanGeo18** [comment]
Please fix this.

**Comment by trichter** [comment]
Can you please post the full error traceback?

**Comment by PawanGeo18** [comment]
Thank you sir for your kind reply.
The following error is displayed (I am attaching the screenshot and the notebook also)

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_27333/1642075846.py in <module>
      6 inventory = read_inventory(invfile)
      7 inventory.plot(label=False)
----> 8 fig = inventory.plot('local', color_per_network=True)

~/anaconda3/envs/myenv/lib/python3.10/site-packages/obspy/core/inventory/inventory.py in plot(self, projection, resolution, continent_fill_color, water_fill_color, marker, size, label, color, color_per_network, colormap, legend, time, show, outfile, method, fig, **kwargs)
   1020                 leg_.prop.set_size("medium")
   1021             # remove collections again solely created for legend handles
-> 1022             ax.collections = ax.collections[:count]
   1023 
   1024         if outfile:

AttributeError: can't set attribute 'collections'

Screenshots of error and code:
![SS1](https://user-images.githubusercontent.com/97451965/148907473-00f01bec-ff5c-4071-92ac-2b4310a9400d.PNG)

![SS2](https://user-images.githubusercontent.com/97451965/148907492-24f56eaa-1131-4054-b633-d23d2e7dd719.PNG)

**Comment by trichter** [comment]
This is an obspy issue. Can you check if it works for obspy development installation?

**Comment by PawanGeo18** [comment]
Thank you sir for kind reply. 
I am unbale to understand this 'Obspy development installation'. How to install it or where can I run this installation?
Please elaborate this.

**Comment by trichter** [comment]
In your conda environment, please try:

```
conda install git
conda uninstall -f obspy
pip install git+https://github.com/obspy/obspy.git
```

**Comment by PawanGeo18** [comment]
Thank you sir for your kind help.
This was an obspy issue. After following your suggestions, it is working properly.
