### ISSUE TITLE
Calculate iterative deconvolution with PREM model

### ISSUE THREAD

**Issue by Thea92** [trichter/rf#41]
Hi all,
at the moment I'm trying to calculate iterative RFs by using the PREM velocity model.
For some distances I get 'empty' receiver functions, it is happening when doing: rfstats(stream, phase=phase, dist_range=dist_range, tt_model=tt_model). My assumption is that there is a problem with the dist_range and the phase. I set P phase with a distance range of 30-95°, Pdiff for 95-105°, PP for 105-140° and PKP for 140-165°, which worked perfectly fine for the RF calculation using the iasp91 model.
Now using the prem model, I get problems with for example distances of 134° and 139°, 134° needs to be associated with a PKP,  but it is not working to associate 139° with the PKP phase. I checked the arrivals using the taupy model, where I get PKP arrivals and I also checked the ray paths using cake. I also tried the phases P, PP, PKP and Pdiff (just to try, when it is working), but the rfstream is  always getting empty after using rfstats.
So, do you have any idea how to solve this problem? Did I miss anything? How can I see, which distance range rf wants me to use for which phase, if it is not conform with the taupy model? 

Any help is very appreciated! Many thanks! :)

**Comment by trichter** [comment]
Hi Thea,

can you post a short code example demonstrating your issue?
Let's also move our discussion to the forum at discourse: 
https://discourse.obspy.org/c/obspy-related-projects/rf

**Comment by Thea92** [comment]
Oh sorry, yes, I created a topic at that forum and included a short part of the code.
Thanks! :)

**Comment by trichter** [comment]
No problem at all :)
