### ISSUE TITLE
AttributeError: 'numpy.int32' object has no attribute 'split

### ISSUE THREAD

**Issue by dip16gphy** [trichter/rf#42]
Hi!
I am getting this error while attempting to run the codes. 
Please help
[
![image](https://user-images.githubusercontent.com/101346054/157784051-448d4445-8700-4046-a905-1eae1e658431.png)
](url)

**Comment by trichter** [comment]
Hi!

This is an obspy issue. See obspy/obspy#2912.

Luckily we just released a new obspy version today which includes a fix for this bug.
So, it should be solved by upgrading obspy to version 1.3.0.

**Comment by dip16gphy** [comment]
Thanks a lot! It worked.
