### ISSUE TITLE
receiver function calculation error

### ISSUE THREAD

**Issue by yjlimm** [trichter/rf#44]
Hello
I want to calculate receiver function by using rf function, but have problem.

When I execute code like your tutorial example ('_rf_iter = stream.copy().rf(deconvolve='iterative', rotate='NE->RT', gauss=1.0_') with my broadband and geophone data, I receive error message '_IndexError: index 2001 is out of bounds for axis 0 with size 2001_'. The number of '2001' may be npts.
 
But, When I practice that function with your tutorial example, there are no error.
I already checked 'stats' by comparing the headers between tutorial example data and my data.

I have searched why I receive that error message using google.
I think the 'Numpy'  has problem... 

I'm python beginner, so don't know how can i treat this problem...

please help me...=( 
I want to calculate receiver function....

Thank you!!

**Comment by trichter** [comment]
Difficult to say what is going wrong. Can you provide a minimal self-consistent example demonstrating your problem? Please also paste the full traceback. Doe you get the same error for other deconvolution methods?

**Comment by yjlimm** [comment]
I found what is problem!

When I use 'rfstats()', the onset is changed. So, receiver function calculation is not executed.
I don't know why the onset is changed.. but, it's ok..=) Because I can calculate receiver function now =)

Thank you for your kindness!!

**Comment by trichter** [comment]
Yes, the onset is set to the arrival of the P or S wave calculated with taupy. Glad, that it is working now.
