### ISSUE TITLE
Time shift for S Receiver Functions 

### ISSUE THREAD

**Issue by geojunky** [trichter/rf#46]
I was wondering if [this](https://github.com/trichter/rf/blob/bccd99759559029af4d533b1ba853fea0527c6a8/rf/deconvolve.py#L125) is appropriate for S RFs since the time shift is muting the signal of interest which arrives before onset. I could get meaningful S RFs by setting the time shift to 0.

**Comment by trichter** [comment]
Hi, thanks for your input! I am not sure, I think I introduced the `tshift` parameter to ensure that the RF peak on the Z or L component is at 0 seconds as it should be. Do you have any code/pictures that demonstrate the problem?

**Comment by geojunky** [comment]
Hi Tom,

Thanks a lot for your very prompt reply. Please see images demonstrating the issue:

![image](https://github.com/trichter/rf/assets/16846225/97dbfcc2-bd80-44b7-a36d-c5eb61e43092)

![image](https://github.com/trichter/rf/assets/16846225/78458916-3694-4cc1-be8d-fa96b18fe030)

**Comment by geojunky** [comment]
Then, when I set `tshift = 0` on line 125 in deconvolve.py, I get the following:

![image](https://github.com/trichter/rf/assets/16846225/4d0135f0-69d1-42ab-a66a-83c06828e7dd)

Thanks a lot for looking into this.

Cheers,
 Rakib

**Comment by geojunky** [comment]
Btw, the above holds for time, freq and iterative deconv methods I've tested so far.

**Comment by trichter** [comment]
Are you sure, you are calculating S receiver functions? If not specified the method is chosen by the phase.

**Comment by geojunky** [comment]
Yes; `phase` in trace stats is set to 'S' and I have also traced through the RF code to ensure S RFs are being computed.

**Comment by geojunky** [comment]
Thanks a lot for the detailed explanation, Tom! My bad; please close the non-issue.

**Comment by trichter** [comment]
No problem at all! Please note that user questions should be posted to the [forum](https://discourse.obspy.org/c/obspy-related-projects/rf). The issue tracker is for bug reports. I see that sometimes it is difficult to decide if a problem is a bug or not.
