### ISSUE TITLE
Synthetic RFs

### ISSUE THREAD

**Issue by santisoler** [trichter/rf#5]
I was wondering if rf is offering some tools to generate synthetic Receiver Functions from a 1D velocity model. If not, is there any tool for doing it? Are we planning to include this kind of functionality in rf?

**Comment by trichter** [comment]
Unfortunately not. But that would indeed be very nice to have!

You can find some tools for calculating synthetic receiver functions, but I cannot recommend any, because I didn't use any of them.

**Comment by paudetseis** [comment]
Just stumbled upon this comment by chance - it's 1.5 years late but you can check out https://github.com/paudetseis/Telewavesim for RF modelling.

**Comment by trichter** [comment]
@paudetseis Just wanted to link your project myself. Thank you for sharing the code!

**Comment by trichter** [comment]
> Are we planning to include this kind of functionality in rf?

It would be nice to have a wrapper around telewavsim and/or similar synthetic RF projects. Though, I do not have the capacity to implement this in the near future.  I am closing this ticket for now., but anybody feel free to repoen if you want to work on this.
