### ISSUE TITLE
RF aggressively catches all exceptions, blocking keyboardinterrupt

### ISSUE THREAD

**Issue by medlin01GA** [trichter/rf#6]
During `iter_event_data`, RF catches all exception types, meaning you can't even stop execution using keyboard interrupt (CTRL-C) since this is of exception type `KeyboardInterrupt`.

Consider narrowing the except catching statements to `except Exception:`, as this is a base class for all the exceptions I think would be intended to be caught here. See [Python exception documentation](https://docs.python.org/2/library/exceptions.html#exception-hierarchy).

This would then allow CTRL-C to interrupt the execution when the user wants it to.

**Comment by trichter** [comment]
Thanks a lot for this feedback.
