### ISSUE TITLE
IterMultipleComponents can apply 'in' to non-iterable

### ISSUE THREAD

**Issue by amedlin** [trichter/rf#9]
https://github.com/trichter/rf/blob/ae1b020428579b69bb83ec40620ba5bab05d369d/rf/util.py#L156

For example if `n` is `int` and `n == 3` and `len(s) = 2`, then the logic will continue through to `len(s) in n`, but `n` being `int` is not iterable, so this raises TypeError: `TypeError: argument of type 'int' is not iterable`

The logic on this line needs to check for iterability before applying `in` to `n`.

**Comment by trichter** [comment]
Thanks, very good point.
